import { StyleSheet } from "react-native";
import { colors } from "../../utilities/colors";

export const styles = StyleSheet.create({
    page: { flex: 1, backgroundColor: '#f5f5f5', padding: 10, width: '100%' },
    card: { marginBottom: 16, borderRadius: 8, overflow: 'visible', borderWidth: 1, borderColor: colors.cardBorder, elevation: 3, },
    cardTitle: { color: colors.primary, fontSize: 16, fontWeight: 'bold', },
    cardSubtitle: { color: colors.primaryLight, marginTop: -5, fontSize: 14, },
    subCard: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.primaryLighter, },
    tableWrapper: { borderTopWidth: 1, borderColor: colors.rowBorder, },
    table: { width: '100%', backgroundColor: colors.white, },
    tableHeader: { backgroundColor: colors.headerBg, height: 48, minWidth: 120, },
    table2Header: { backgroundColor: colors.headerBg, height: 48, width: 1360, },
    table3Header: { backgroundColor: colors.headerBg, height: 48, minWidth: 1190, },
    columnHeader1: { minWidth: 170, justifyContent: 'flex-start', alignItems: 'flex-start', },
    columnHeader2: { minWidth: 150, justifyContent: 'flex-start', alignItems: 'flex-start', },
    columnHeader3: { minWidth: 150, justifyContent: 'flex-start', alignItems: 'flex-start', },
    columnHeader4: { minWidth: 170, justifyContent: 'flex-start', alignItems: 'flex-start', },
    columnHeader5: { minWidth: 100, justifyContent: 'flex-start', alignItems: 'flex-start', },
    columnHeader6: { minWidth: 100, justifyContent: 'flex-start', alignItems: 'flex-start', },
    columnHeader7: { minWidth: 100, justifyContent: 'flex-start', alignItems: 'flex-start', },
    columnHeader8: { minWidth: 100, justifyContent: 'flex-start', alignItems: 'flex-start', },
    columnHeader9: { minWidth: 170, justifyContent: 'flex-start', alignItems: 'flex-start', },
    columnHeader10: { minWidth: 170, textAlign: 'center', justifyContent: 'center', alignItems: 'center', },
    columnHeader11: { minWidth: 250, justifyContent: 'flex-start', alignItems: 'flex-start', },
    columnHeader12: { minWidth: 170, justifyContent: 'flex-start', alignItems: 'flex-start', },
    columnHeader13: { minWidth: 170, justifyContent: 'flex-start', alignItems: 'flex-start', },
    columnHeader14: { minWidth: 170, justifyContent: 'flex-start', alignItems: 'flex-start', },
    column2Header1: { width: 170, justifyContent: 'flex-start', alignItems: 'flex-start', },
    column2Header2: { width: 170, justifyContent: 'flex-start', alignItems: 'flex-start', },
    column2Header3: { width: 170, justifyContent: 'flex-start', alignItems: 'flex-start', },
    column2Header4: { width: 170, justifyContent: 'flex-start', alignItems: 'flex-start', },
    column2Header5: { width: 170, justifyContent: 'flex-start', alignItems: 'flex-start', },
    column2Header6: { width: 170, justifyContent: 'flex-start', alignItems: 'flex-start', },
    column2Header7: { width: 170, justifyContent: 'flex-start', alignItems: 'flex-start', },
    column2Header8: { width: 170, justifyContent: 'flex-start', alignItems: 'flex-start', },
    column3Header1: { width: 170, justifyContent: 'flex-start', alignItems: 'flex-start', },
    column3Header2: { width: 170, justifyContent: 'flex-start', alignItems: 'flex-start', },
    column3Header3: { width: 170, justifyContent: 'flex-start', alignItems: 'flex-start', },
    column3Header4: { width: 170, justifyContent: 'flex-start', alignItems: 'flex-start', },
    column3Header5: { width: 170, justifyContent: 'flex-start', alignItems: 'flex-start', },
    column3Header6: { width: 170, justifyContent: 'flex-start', alignItems: 'flex-start', },
    column3Header7: { width: 170, justifyContent: 'flex-start', alignItems: 'flex-start', },
    headerText: { color: colors.primary, fontWeight: 'bold', textAlign: 'left', fontSize: 14, },
    tableRow: { borderBottomWidth: 1, borderBottomColor: colors.rowBorder, height: 50, minWidth: 120, },
    table2Row: { borderBottomWidth: 1, borderBottomColor: colors.rowBorder, height: 50, width: 1360, },
    table3Row: { borderBottomWidth: 1, borderBottomColor: colors.rowBorder, height: 50, minWidth: 1190, },
    tableCell: { alignItems: 'flex-start', justifyContent: 'center', paddingLeft: 8, height: 50, minWidth: 120, },
    tableCell1: { minWidth: 170, alignItems: 'center', justifyContent: 'center', height: 50, },
    tableCell2: { minWidth: 150, alignItems: 'center', justifyContent: 'center', height: 50, },
    tableCell3: { minWidth: 150, alignItems: 'center', justifyContent: 'center', height: 50, },
    tableCell4: { minWidth: 170, alignItems: 'center', justifyContent: 'center', height: 50, },
    tableCell5: { minWidth: 100, alignItems: 'center', justifyContent: 'center', height: 50, },
    tableCell6: { minWidth: 100, alignItems: 'center', justifyContent: 'center', height: 50, },
    tableCell7: { minWidth: 100, alignItems: 'center', justifyContent: 'center', height: 50, },
    tableCell8: { minWidth: 100, alignItems: 'center', justifyContent: 'center', height: 50, },
    tableCell9: { minWidth: 170, alignItems: 'center', justifyContent: 'center', height: 50, },
    tableCell10: { minWidth: 170, alignItems: 'center', justifyContent: 'center', height: 50, },
    tableCell11: { minWidth: 250, alignItems: 'center', justifyContent: 'center', height: 50, },
    tableCell12: { minWidth: 170, alignItems: 'center', justifyContent: 'center', height: 50, },
    tableCell13: { minWidth: 170, alignItems: 'center', justifyContent: 'center', height: 50, },
    tableCell14: { minWidth: 170, alignItems: 'center', justifyContent: 'center', height: 50, },
    table2Cell1: { width: 170, alignItems: 'center', justifyContent: 'center', height: 50, },
    table2Cell2: { width: 170, alignItems: 'center', justifyContent: 'center', height: 50, },
    table2Cell3: { width: 170, alignItems: 'center', justifyContent: 'center', height: 50, },
    table2Cell4: { width: 170, alignItems: 'flex-start', justifyContent: 'flex-start', height: 50, },
    table2Cell5: { width: 170, alignItems: 'center', justifyContent: 'center', height: 50, },
    table2Cell6: { width: 170, alignItems: 'center', justifyContent: 'center', height: 50, },
    table2Cell7: { width: 170, alignItems: 'center', justifyContent: 'center', height: 50, },
    table2Cell8: { width: 170, alignItems: 'center', justifyContent: 'center', height: 50, },
    table3Cell1: { width: 170, alignItems: 'center', justifyContent: 'center', height: 50, },
    table3Cell2: { width: 170, alignItems: 'center', justifyContent: 'center', height: 50, },
    table3Cell3: { width: 170, alignItems: 'center', justifyContent: 'center', height: 50, },
    table3Cell4: { width: 170, alignItems: 'flex-start', justifyContent: 'flex-start', height: 50, },
    table3Cell5: { width: 170, alignItems: 'center', justifyContent: 'center', height: 50, },
    table3Cell6: { width: 170, alignItems: 'center', justifyContent: 'center', height: 50, },
    table3Cell7: { width: 170, alignItems: 'center', justifyContent: 'center', height: 50, },
    cellText: { textAlign: 'left', color: '#333', fontSize: 14, width: '100%' },
    selectedRow: { backgroundColor: colors.primaryBackground, },
    tableButton: { height: 30, paddingVertical: 0, borderWidth: 1, borderColor: colors.primaryLight, borderRadius: 4, },
    tableButtonLabel: { fontSize: 12, marginVertical: 0, paddingVertical: 0, },
    pagination: { backgroundColor: colors.white, borderTopWidth: 1, borderTopColor: colors.rowBorder, paddingVertical: 8, paddingHorizontal: 16, flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', },
    modal: { backgroundColor: colors.modalBg, padding: 24, margin: 20, borderRadius: 8, borderWidth: 1, borderColor: colors.primaryLighter, },
    modalTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 16, color: colors.primary, },
    modalText: { fontSize: 14, marginBottom: 8, color: '#333', },
    modalButtons: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 24, gap: 12, },
    modalButton: { borderColor: colors.primaryLight, },
    noteCard: { marginTop: 8, marginBottom: 16, borderWidth: 1, borderColor: colors.cardBorder, backgroundColor: colors.white, },
    noteTitle: { fontSize: 16, fontWeight: 'bold', marginBottom: 12, color: colors.primary, },
    noteInput: { marginBottom: 16, backgroundColor: colors.white, },
    saveButton: { alignSelf: 'flex-end', },
    avatarContainer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start', height: 50, width: '100%', },
    avatar: { marginRight: 8, borderRadius: 20, },
    filterContainer: { flexDirection: 'row', marginBottom: 10, position: 'relative' },
    searchInput: { flex: 1, backgroundColor: colors.white, height: 40, paddingLeft: 25, },
    inputIcon: { position: 'absolute', top: 10, left: 10, zIndex: 1001 },
    resultCount: { marginRight: 14, color: colors.primaryLight, },
    emptyRow: { height: 100, borderBottomWidth: 1, borderBottomColor: colors.rowBorder, },
    emptyMessage: { textAlign: 'center', color: '#888', fontSize: 16, },
    uploadingContainer: { alignItems: 'center', marginVertical: 20, padding: 15, },
    uploadingText: { marginTop: 10, fontSize: 16, color: colors.primary, },
    noteModalBtn: { borderColor: colors.primary, borderWidth: 1, backgroundColor: 'transparent', borderRadius: 4, paddingVertical: 8, paddingHorizontal: 16, },
    noteModalBtnTxt: { color: colors.primary, },
    noteHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexDirection: 'row' }
});